### ISSUE TITLE
Logo source file?

### ISSUE THREAD

**Issue by sindresorhus** [bitcoinhush/bitcoinhush.github.io#10]
Where can I find the source file or SVG (not PNG) of the project logo?

I would like to submit it to https://github.com/cjdowner/cryptocurrency-icons

**Comment by leto** [comment]
@sindresorhus I will see what I can find

**Comment by sindresorhus** [comment]
@leto Any updates?

**Comment by leto** [comment]
This might be useful to somebody working on this: 

https://github.com/peterqard/bitcoinhush.github.io/tree/master/logo-assets

**Comment by gilardh** [comment]
Here is a lot of logo in version SVG :
[SVG Version.zip](https://github.com/bitcoinhush/bitcoinhush.github.io/files/2341213/SVG.Version.zip)

Tell me if it suits you.

**Comment by sindresorhus** [comment]
@gilardh Thank you! That's perfect.

I would recommend adding the SVG versions to https://github.com/peterqard/bitcoinhush.github.io/tree/master/logo-assets

**Comment by gilardh** [comment]
Here is a new version with a lighter file weight of 15% on average :
[SVG Version.zip](https://github.com/bitcoinhush/bitcoinhush.github.io/files/2343673/SVG.Version.zip)

I asked to add these files using a commit :
https://github.com/peterqard/bitcoinhush.github.io/pull/1
