### ISSUE TITLE
Update link of BTCH website

### ISSUE THREAD

**Issue by gilardh** [bitcoinhush/bitcoinhush.github.io#12]
In this page : https://github.com/bitcoinhush/bitcoinhush.github.io, the weblink 'https://btchush.org' is not correct.

It is necessary to replace
Bitcoin Hush: BTCH, The Immaculate Merge Drop **https://btchush.org**
with
Bitcoin Hush: BTCH, The Immaculate Merge Drop **https://bitcoinhush.github.io/**

**Comment by leto** [comment]
@gilardh thanks, fixed!

**Comment by gilardh** [comment]
@leto I was talking about the internet link above. ;o)

![Screenshot_20191014-090021_Chrome](https://user-images.githubusercontent.com/39105646/66735910-05a1a580-ee68-11e9-921a-570b69b3083b.jpg)
